sources:
- name: cisco-devices
  hosts:
    - url: ssh://admin:Metrolink96$@10.120.0.1 devtype=iosxe
    - url: ssh://admin:Metrolink96$@10.120.0.2 devtype=iosxe
    - url: ssh://admin:Metrolink222@10.120.0.29
    - url: ssh://admin:Metrolink222@10.120.0.30

devices:
- name: default-settings
  ignore-known-hosts: true

namespaces:
- name: default
  source: cisco-devices
  device: default-settings
