CREATE USER topo WITH PASSWORD 'topo';
CREATE DATABASE topology OWNER topo;
GRANT ALL PRIVILEGES ON DATABASE topology TO topo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO topo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO topo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO topo;
